name: Create Jira Ticket Create
on:
  push:
    branches:
      - master

jobs:
  create_ticket:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Create Jira Ticket
      env:
        JIRA_BASE_URL: https://iseki.atlassian.net
        JIRA_PROJECT_KEY: KAN
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN2 }}
      run: |
        ticket_data='{
          "fields": {
            "project": {
              "key": "'${{ env.JIRA_PROJECT_KEY }}'"
            },
            "summary": "New Issue Created by GitHub Actions",
            "description": "This issue was created automatically by GitHub Actions.",
            "issuetype": {
              "name": "Task"
            }
          }
        }'
        
        response=$(curl -s -X POST \
          -H "Authorization: Basic $JIRA_API_TOKEN" \
          -H "Content-Type: application/json" \
          --data "$ticket_data" \
          ${JIRA_BASE_URL}/rest/api/3/issue/)
        echo "Created Jira ticket: $response"
